baseurl = "http://www.610yesnolovely.com/"
title = "610YesNoLovely"
languageCode = "en-us"
disqusShortname = "610yesnolovely" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Harvey Thompson"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Six foot ten, yes, no, lovely."
    defaultKeywords = "blog,programming"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "solarized_light"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Six foot ten, yes, no, lovely."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAuthorship = ""
    googleAnalytics = ""
    gravatarHash = "fb160cfa1c54281837536ba596df5c31"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/harveyt"
    bitbucket = "https://bitbucket.org/harveyt"
    stackOverflow = "http://stackexchange.com/users/6200113/harvey-thompson"
    linkedin = "https://ca.linkedin.com/pub/harvey-thompson/1/852/b76"
    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/610yesnolovely"
    youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
#    flattr = ""  # populate with your flattr uid
